### PR TITLE
adds flight fitness function and description

### PR DESCRIPTION
**Pull request by madammann**
The fitness function for flight is done now.
I hope you find my comments and the description in the markdown area above helpful.
Tell me what you think or would like to have changed :)

### CODE REVIEW

**Comment by madammann** [comment]
I forgot I also changed some part in the dinosaur generator on top as well.
It was giving me a list of tuples for each value and I was not sure whether that is what was intended.
I thought we wanted a list of floats so I changed it.
Do you want to keep my changes or would you prefer a list of tuples instead?

**Review by FaKock — APPROVED** [review]
Hi Marlon,

Your flee function looks great. I really like that you added a function description.
Regarding the tuples, I changed that as well for my fitness functions, so floats are great!
My only concern is that we will never get an aggression larger than 100 so maybe just make a >= out of it in your aggression part.

Overall, this leaves me with the question, if I should adapt fight and hunt to reflect a similar scale as you have? I currently start at 1 and my result stays quite small...

Best,
Fabienne

**Comment by madammann** [comment]
Hi Fabienne,
I changed the comparison error you pointed out.

The scales should ideally be close, you are right.
What would you prefer, should I change my scale or should we change yours?
Also we may need to be careful to disallow a negative fitness as well and introduce a lower bound of 0.

Best,
Marlon

**Comment by FaKock** [comment]
Hi Marlon,

I think we can change mine, sinceI also need to prevent fitness below 0 as well.
I'd start on that now and update my branch :)

Best,
Fabienne

**Comment by pippowell** [comment]
Function looks good. My only question is the same range question that has cropped up in several areas. I'll elaborate in Telegram.

**Pull request merged**
