### PR TITLE
Finalizing Sheet

### PR DESCRIPTION
**Pull request by pippowell**
- removes code
- updates text
- standardizes variable names
- adds docstrings & instructions
- adds cost_function block, de_algorithm implementation block, and algorithm test block

### CODE REVIEW

**Review by FaKock — APPROVED** [review]
Looks fine to me. I really like all the comments and descriptions! Just a short question, has anyone saved the final version with all functions, so we have an example solution?

**Review by IngaKristin — APPROVED** [review]
Looks great to me! But, we should make sure that we have the untouched verion as a solution somewhere, before merging.

**Review by mheyen — APPROVED** [review]
very much approved!
besides one little thing: 
The ranges: 

(0 - 24) - Ooh La La! 
(25 - 49) - Dateable 
(50 - 74) - In The Right Clothes, Maybe… 
(75 - 100) - Well, no takers now, but take some time to become your best self and try again later. :) 

should be inverted, right? 
100 is the best and 0 is the worse

**Review by madammann — APPROVED** [review]
Great job!
One thing to add is that the selection function is still missing its "pass" statement and we should probably delete all chell outputs before we submit it.
Everything else which I would add has already been addressed by the others.

**Review by Hind-Shalfeh — APPROVED** [review]

**Pull request merged**
