### PR TITLE
Selection

### PR DESCRIPTION
**Pull request by mwassermann**
Includes the population initialization, the selection function and some changes to the text for selection

### CODE REVIEW

**Review by FaKock — COMMENTED** [review]
Hi Max,

I think a general problem here is that quite a lot of changes happened on the main that are of an older version on your branch.

Your parent selection function looks fine to me. Just a short question at the other reviewers as well, don't we want to minimize the fitness since we use it as a cost function (at least the presentation says so). If so, you would need to reverse the greater than sign (>) into <.

Regarding the create population function:
I think you can simplify the creation of a T-Rex by using createrex(). It basically initializes a Dino with all 7 traits, similar to how you do it in the for loop. 
Furthermore, you do not necessarily need ti intantiate an array of the population size. If you create the population as an empty list you can simply use population.append(createrex()) to grow the population to the size you need. 

Thanks for your work! Best,
Fabienne

**Review by FaKock — APPROVED** [review]
Both cross_over and evolve_rex look good to me.

**Review by mheyen — APPROVED** [review]
I think this looks good :) 

I would have some minor adjustments, but I think it's easier to merge this now and go over it once at the end if everything else is done

**Comment by pippowell** [comment]
All functions added in this merge (population initialization, selection, crossover, and the main function) look good to me, but as crossover and the main function were assigned to other team members, I would like to get their approval before merging this. I will mention this in the Telegram chat.

**Pull request merged**
