### PR TITLE
initial implementation of programming task 1

### PR DESCRIPTION
**Pull request by FaKock**

### CODE REVIEW

**Review by annassommer — APPROVED** [review]
Code looks good, well explained and runs correctly for me. I'd say it's good.

**Comment by mwassermann** [comment]
so in each step we only add 1 new random center position, then delete the center at the first position and return this new list of centers only when it is an improvement, otherwise return the old one, right?

if that is what this function is supposed to do, it works

**Comment by FaKock** [comment]
@mwassermann currently it adds only one new random center position, but you should be able to increase the number. In the second step it removes currently, since we only add one node one center position from the array, but it does that once for each index of the expanded center position array, calculating each time the critical_pair. If it is an improvement it is the new best, if not the old best stays . If we added more than one new center position it will remove in each loop over the expanded positions array the number of new center positions from the current index onward. 
I hope that explains my thought process behind the code...

**Comment by mwassermann** [comment]
@FaKock aaa that makes much more sense. so it tries every combination of 5 positions from the expanded centers and chooses the best one? that seems way better than just deleting a random one.

but the for loop is currently only being run 1 time(for i in range(expansion)). shouldnt it be something like for i in range(p_centers + expansion) or am I misunderstanding something here?

**Comment by FaKock** [comment]
@mwassermann you're right. That loop needs to be adapted to p_centers. If you go higher it might lead to an index out of bounds error. I adapted it!

**Pull request merged**
