### PR TITLE
transitions_function

### PR DESCRIPTION
**Pull request by FaKock**
small change to create new branch that can be merged into antcolony to create a proper merge request

### CODE REVIEW

**Comment by madammann** [comment]
Dear Reviewers,

some of the code was accidentally already pushed to the Antcolony branch.
Please read through the code (the commit history probably does not show changes properly) and make suggestions or changes on this branch.
After this is resolved I will merge everything properly.

Best,
Marlon

**Comment by pippowell** [comment]
We'll need to check with Crew B tomorrow about the neighbors function. As is, this code will not actually work as it will try to iterate through self.node, which is actually just one node that is the current position of the ant to my understanding. We will need it to iterate through the ant's neighboring nodes. The True/False output there may not be an indication that the self.neighbors function is not working, but rather a built-in check if there neighbors at all, or something similar. Crew B can confirm. 

The calculation looks fairly good except that I believe the command is edge.pheromone (without the s).

**Comment by FaKock** [comment]
@pippowell I thought, based on the example in Grap_Example, that iterating over a node gives the neighbors. That is why I iterated over self.node. Does that not work for the Ant class?

**Comment by pippowell** [comment]
Looked at the updated code. Thanks for updating so quickly!

My thoughts/observations:

The iteration over self.node isn't an issue as discussed in the session this morning (my misunderstanding there). 

However, I would suggest moving the checking of whether the nodes have been visited up to this point in the code. Right now, the sum_available is still looking at ALL nodes and not just the true neighbors (i.e. excluding those we can't travel to because they've already been visited or are the node we're at now). Looking at the slides again, it seems like this sum should only count "available edges," which would presumably be only the edges to neighbor nodes. 

In the if statement, should it be "if self.neighbours(nodes[n]) == True"? At the least, I believe you need an "s" at the end of neighbours. 

Minor point - we can remove the comment at the top about not using the neighbours function, and make sure all the comments are in line with our current thinking ("get all neighbors" for instance is above the line of code that is actually not excluding the already visited nodes yet). 

If the above changes are made, we can drop the neighbor_nodes list and just use the nodes list I would say, since we won't need to be checking against the nodes list separately if the exclusion of non-neighbors is done in the same block (ex. "for n in self.node / if self.neighbours..."), and then we can return the nodes and probabilities lists as requested in the instructions for the class (though of course the name isn't necessarily an issue on its own, it's just good to follow the requests as closely as possible).

**Comment by pippowell** [comment]
Also, thank you for updating the reset function on your branch. Looks good now. :)

**Review by mheyen — APPROVED** [review]
looks fine :)

**Review by madammann — CHANGES_REQUESTED** [review]
Hi, thanks for your current submission.
Two small changes need to be implemented before this function can be merged into antcolony.

## Check variable names
if self.neighbour(nodes[n]) --> if self.neighbour**s**(nodes[n])
neighbor_node.append --> neighbor_node**s**.append

Try to stick to **neighbour** instead of neighbor for consistency.

## Check case handling
If sum_available is 0, then probabilities becomes a NaN array.
This in itself is not a problem, however, the case for values not being present yet needs to be handled somewhere, ideally here.
Maybe make a conditional that if sum_available is 0, then probabilities becomes uniformly distributed over all options.

**Review by kavya-sivakumar — APPROVED** [review]

**Review by madammann — APPROVED** [review]

**Pull request merged**
