### PR TITLE
Backward pass

### PR DESCRIPTION
**Pull request by Hind-Shalfeh**

### CODE REVIEW

**Comment by mwassermann** [comment]
o_max is not the value of o_b while fitness is maximum. You have to first calculate the whole list of o_b and then look for the maximum value of that list.

and does max(fitness) do anything? I would write it as fitness.max()

**Review by FaKock — COMMENTED** [review]
A general remark, I tried to run it, but had to fix some indentations both for the critical pair and your backwards pass. For a def you always have an indent of the code respective to the def. 
Otherwise the backwards_pass is currently not running for me and I'm currently trouble shooting.

**Comment by madammann** [comment]
Hi Hind,

I have looked at and tested the code now.
First of all the code looks correct content-wise.
However, just as Fabienne wrote a few minutes ago the indentations of your backward pass function are one too much to the left.
Secondly, just as Fabienne, I am having trouble with the critical pair function run in the forward pass.
I will also take a look and try to figure out what went wrong now.

Best,
Marlon

**Comment by FaKock** [comment]
I've got the backwrd pass function running. I had to adapt the roulette wheel a bit as well, since there appeared problems. I'm currently running the whole code once and had a successful first iteration.Afterwards it seems to level. Shall I push my changes here or create another branch?

**Comment by pippowell** [comment]
For now, push the changes to another branch so we have one working solution pending without deleting the code that Marlon etc. are looking at. 

A version of the sheet has actually already been updated, but we can upload a second copy as well if everything works better with the new changes.

**Comment by Hind-Shalfeh** [comment]
@mwassermann I tried fitness.max() since I saw it your code, but it didn't work , and according to the python dosumentation it is max(fitness)
for the o-max part I calculated like this : o_max = normalize_value(objective, fmax, fmax, fmin)

**Comment by Hind-Shalfeh** [comment]
@FaKock it's weird , because in my broweser the identation is correct in backward_pass 
and I also had to fix identation in the critical pair and pushed it :/

**Comment by FaKock** [comment]
@Hind-Shalfeh maybe the indenation differs from browser to browser? As long as everything is similar in the formatting and working I don't think that will make much of a problem :)

**Comment by Hind-Shalfeh** [comment]
@madammann Hi Marlon,
Excatly the critical pair function in the forward pass is provided by the Bee Colony Team and should work! it was really frustrating not being able to run the code due to errors on their part.

**Pull request merged**
