### PR TITLE
Add Step Function

### PR DESCRIPTION
**Pull request by pippowell**
Adds the step function referencing the transitions function (use of edge command will need to be checked with Crew B). I am not sure which command is best to use for creating an edge (self.graph could be an option too?).

### CODE REVIEW

**Comment by pippowell** [comment]
The latest update changes the command from "edge" to "self.edge" since the former isn't recognized as a command. The code here also checks whether the node identified as the one to move to is one that is already visited. This is also handled implicitly via the transitions() function, but based on their instructions and info from this morning's session, this seems to be what they are getting at in terms of it returning True/False if a step was/wasn't taken. 

Further thought particularly on the edge creation line and the True/False output is very welcome. :)

**Review by mheyen — APPROVED** [review]
looks fine :)

**Review by IngaKristin — APPROVED** [review]
That looks good to me :)

**Comment by madammann** [comment]
Hi, thanks for implementing the function.
Although not testable without the transitions function yet, it should work properly and do what it is supposed to.
Please consider these two points though before we merge and make a small commit or message.

- The visualization part may need _self.travel_distance_ to be incremented here as well.

- Currently we chose the node with highest probability but maybe we should instead choose a random node weighed by probability, I do not know 100% which was intended here.

One option could be using _np.random.choice(list, p=p)_, where p is a list of probabilities for each element in list.
Additionally sum(p) ~= 1.

It would be nice if you could check briefly whether these points need to be addressed, alternatively we could also merge and, if any anomalies arise, revisit these points.

Best,
Marlon

**Comment by pippowell** [comment]
Thank you for reviewing and providing detailed feedback!

My thinking on the two points:


1. I believe the distance may be implicitly handled in the edge command, since it takes the start and destination nodes as arguments and the distances between respective nodes are predefined to my knowledge. 

2. Usually we take the highest probability. I would say that is a safe assumption here and I don't think there was anything in their presentation which said we should do differently. 

Those points being said, I would say let's merge this and then I'll make sure to watch the chat if any odd behavior crops up in the later functions that could be traced back to an issue in the step command.

**Pull request merged**
